export const CHECK_AUTH_STATUS_NONE = 'CHECK_AUTH_STATUS_NONE';
export const CHECK_AUTH_STATUS_RECEIVED = 'CHECK_AUTH_STATUS_RECEIVED';
export const CHECK_AUTH_STATUS_WAITING = 'CHECK_AUTH_STATUS_WAITING';
